version: '2.1'

services:
  cci-ubuntu: &defaults
    image: cryptoplay/cci-ubuntu
    build:
      context: src/
    read_only: true
    cap_drop:
      - all
    cpu_shares: 1023
    mem_limit: 1G
    shm_size: 32M
    stdin_open: true
    tty: true

  ci:
    <<: *defaults
    entrypoint: goss
    command: -g /goss.yaml validate --format=tap
